### ISSUE TITLE
Raw or Logical Units with Get

### ISSUE THREAD

**Issue by aussiebj** [al-fontes-jr/bardolph#1]
Hi,

Is there a way I can retrieve logical units from the get command or is this a bug ? The following script only works if I put a "units raw" before and a "units logical" after each get command 

<img width="521" alt="ss" src="https://user-images.githubusercontent.com/66948643/84650276-41d35b80-af4b-11ea-8530-b0128ca30fb2.png">

The last set command is trying to set values to 32211108 and 42948362 !

Also, a print command to output variables to the log and a way of getting the set and get values to the log for real lights as well would be nice. But very good work in general.

**Comment by al-fontes-jr** [comment]
Logged output feature as issue #2.

**Comment by al-fontes-jr** [comment]
Thanks very much for reporting this. It was definitely a bug. Should be fixed, now.
