### ISSUE TITLE
Python docs no longer match module

### ISSUE THREAD

**Issue by epleterte** [al-fontes-jr/bardolph#11]
Hey,

the example for python looks like this (from https://bardolph.org/doc/docs/python_interface.html - this differs slightly from the README):

```
from bardolph.controller import ls_module

ls_module.configure()
ls_module.queue_script('time 1 all on')
ls_module.queue_script('time 5 all off')
```

...but ls_module does not exist anymore. Looking at the unit tests (and the code), I see `light_set` instead. The `queue_script` function seems to be long gone.

Anyway - just adding an issue to point out docs need updating!

**Comment by al-fontes-jr** [comment]
Thanks so much for the bug report. It should be back where it belongs now. I've also updated the docs and added a couple of examples.

I had removed the module (temporarily, I had planned) while I was re-working the job control code, and forgot to update it.

**Comment by epleterte** [comment]
@al-fontes-jr  That is super! Thanks a lot! :)
