### ISSUE TITLE
Support for Candle colour zones

### ISSUE THREAD

**Issue by xserve222** [al-fontes-jr/bardolph#14]

**Comment by al-fontes-jr** [comment]
Can you please supply more detail?

Although I haven't tested it with a Candle Light, I believe it should be accessible with the zone keyword, which has been tested with a Z LED Strip. For more info, please see [](https://bardolph.org/doc/docs/language.html#multi-zone-lights)

**Comment by al-fontes-jr** [comment]
Closing this issue. Please re-open if appropriate.
