### ISSUE TITLE
Global Variables not being set within subroutine

### ISSUE THREAD

**Issue by aussiebj** [al-fontes-jr/bardolph#5]
The last set command should set hue to 50 which should be the updated value for variable y

<img width="515" alt="ss" src="https://user-images.githubusercontent.com/66948643/85419080-f6f1bd80-b5b4-11ea-8e8e-65b7d28a03d6.png">

**Comment by aussiebj** [comment]
Thanks !

**Comment by al-fontes-jr** [comment]
Thanks for reporting the bug.
